### PR TITLE
WeasyPrint convert to pdf

### PR DESCRIPTION
**Pull request by SimonYiJES**
Removed jspdf and uses WeasyPrint with DJango template

### CODE REVIEW

**Comment by swcurran** [comment]
@SimonYiJES - merged this.  I am not able to do a review of the code, so it was a fingers-crossed merge :-). 
 Hopefully you will be able to look at it when it deploys to dev to make sure you are happy with what you see. Let me know if you need to do further revisions.

**Comment by SimonYiJES** [comment]
Hi Stephen, 
It has been built on my local machine. 
It seems I need a log in info to go to the FPO. 

I do not need it right now but if you let me know how to log in tomorrow, it would be awesome. I will check the site tomorrow. 
Have a great dinner and night!


Simon Yi | Web Coordinator



Justice Education Society of BC
#260 - 800 Hornby Street, Vancouver, BC V6Z 2C5
www.JusticeEducation.ca  T 604-660-0660

**Comment by SimonYiJES** [comment]
Oh, and please let me know when you deploy it to dev. 

Simon Yi | Web Coordinator



Justice Education Society of BC
#260 - 800 Hornby Street, Vancouver, BC V6Z 2C5
www.JusticeEducation.ca  T 604-660-0660

**Comment by swcurran** [comment]
Deploys happen automagically. Django and the frontend autodeployed at
5:37PM last night, so you are good to go.

**Pull request merged**
